### ISSUE TITLE
HTML in results?

### ISSUE THREAD

**Issue by amccloud** [fizx/parsley#2]
Would it be possible to select an element and not strip X tags from the results, leaving the formatting in place? Also, it would be nice to ignore certain tags entirely, like "script". Right now, i'm getting javascript in the pages i'm parsing from bestbuy.com. My last suggestion is to replace tags that are removed with a single space so that you have some sort of separation between two elements like "p" tags. As of now, you get run on sentences or words when tags are stripped.

**Comment by fizx** [comment]
There's a function called with-newlines() that does exactly what you want.  It returns innerText(), but excluding style and script tags, and with a newline character replacing the end tags for br, address, blockquote, center, dir, div, form, h1, h2, h3, h4, h5, h6, hr, menu, noframes, noscript, p, pre, li, td, th, and p.

Also, there's inner-xml() and outer-xml() functions which work in an HTML context.  They will return tidied XHTML, not the original.

**Comment by amccloud** [comment]
According to parselets.com function inner-xml and outer-xml raises this error "function inner-xml not found".

**Comment by fizx** [comment]
inner-xml and outer-xml are within the "lib" namespace.  See, the test/outer-xml.\* test cases.

```
{
    "foo": "lib:outer-xml(p)",
    "both": [ "lib:outer-xml(p)" ],
    "inner": "lib:inner-xml(body)"
}
```
